### ISSUE TITLE
RFE: onboard_enabled properties executed through the rest API as opposed to local shell

### ISSUE THREAD

**Issue by kreynoldsf5** [f5devcentral/f5-bigip-runtime-init#3]
pre_onboard_enabled and post_onboard_enabled ```commands``` are currently executed with a local shell. This is generally fine when running on the BIG-IP. When running remotely (on a linux host, container, etc.) this functionality is not as useful. If the properties' ```commands``` were executed against the iCR endpoints (/mgmt/tm/util/bash) for the specified ```host``` they could be used locally and remotely in a predictable manner.

```yaml
runtime_parameters: []
pre_onboard_enabled: []
extension_packages:
  install_operations: []
extension_services:
  service_operations: []
post_onboard_enabled:
  - type: inline
    commands:
      - echo 'currently on a linux host'
      - tmsh revoke sys license
      - echo 'it'd be nice to not make an out-of-band rest call for the above command'
host:
  address: ${bigip_mgmt}
  port: ${bigip_port}
  protocol: https
  username: admin
  password: ${seed_password}
```

Or, in the alternative, another set of properties could be added for remote command execution. My thinking here is it would be desirable to present a single interface for interacting with a BIG-IP device. Ideally, operations like revoking a license (currently not possible for a standalone regkey with DO) would be done through this one interface. Allowed pre and post command execution would also give users much flexibility with respect to DO.
